<?php
/**
 *
 * SetConfigModel.class.php
 *
 * 后台接口模块 - 获取app_info的model
 *
 * Mr.yh @ 2020.10.21
 * 
 */
 
namespace AdminApi\Model;

class SetConfigModel{
	public function initObjects($object_name=''){
		return $objects = array(
			array(
				'object_name'		=> "GET_SEQUENCES",
				'object_type'		=> "FUNCTION",
				'object_value'		=> array(
					"create or replace function get_Sequences(p_table IN VARCHAR) return number
Authid CURRENT_USER 
AS
PRAGMA AUTONOMOUS_TRANSACTION;

	FunctionResult number;
	v_count NUMBER(1);
	v_up_table VARCHAR2(30);
	v_sql Varchar2(2000);
BEGIN
	IF p_table IS NOT NULL THEN 
		v_up_table := upper(p_table);
	ELSE
		raise_application_error(-20201, 'Table name is need!');
	END IF;	

	SELECT COUNT(1) INTO v_count 
	FROM user_sequences
	WHERE SEQUENCE_NAME ='SEQ_'||v_up_table;
	
	IF v_count=0 THEN
		v_sql := 'CREATE SEQUENCE SEQ_'|| v_up_table || ' minvalue 1 NOMAXvalue START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 10';
		EXECUTE IMMEDIATE v_sql;
	END IF;
	
	
	v_sql := NULL;
	v_sql := 'SELECT SEQ_'||v_up_table||'.nextval FROM dual';
	EXECUTE IMMEDIATE v_sql INTO FunctionResult;

	return(FunctionResult);
end get_Sequences;",
				),
			),

			array(
				'object_name'		=> "DICT_TABLES",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table DICT_TABLES
(
	id           NUMBER(10) constraint pk_dict_tables primary key,
	ownerid      NUMBER(10),
	modifierid   NUMBER(10),
	creationdate DATE,
	modifieddate DATE,
	isactive     CHAR(1) default 'Y' not null,
	table_name   VARCHAR2(30) not null,
	title        VARCHAR2(255),
	notes        VARCHAR2(2000),
	is_menu      CHAR(1) default 'N' not null
)",
					"comment on column DICT_TABLES.table_name is '表名'",
					"comment on column DICT_TABLES.title is '描述'",
					"comment on column DICT_TABLES.notes is '注释'",
					"comment on column DICT_TABLES.is_menu is '是否菜单'",
				),
				// 'columns_list'		=> array(
				// 	array(
				// 		'columns_name'	=> 'id',
				// 		'data_type'		=> 'NUMBER(10)',
				// 		'primary_key'	=> '',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'ownerid',
				// 		'data_type'		=> 'NUMBER(10)',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'modifierid',
				// 		'data_type'		=> 'NUMBER(10)',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'creationdate',
				// 		'data_type'		=> 'DATE',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'modifieddate',
				// 		'data_type'		=> 'DATE',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'isactive',
				// 		'data_type'		=> 'CHAR(1)',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'table_name',
				// 		'data_type'		=> 'VARCHAR2(30)',
				// 		'comment'		=> '表名',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'title',
				// 		'data_type'		=> 'CHAR(1)',
				// 		'comment'		=> '表名',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'notes',
				// 		'data_type'		=> 'CHAR(1)',
				// 		'comment'		=> '表名',
				// 	),
				// 	array(
				// 		'columns_name'	=> 'is_menu',
				// 		'data_type'		=> 'CHAR(1)',
				// 		'comment'		=> '表名',
				// 	),
				// ),
			),

			array(
				'object_name'		=> "DICT_COLUMNS",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table DICT_COLUMNS
(
	id             NUMBER(10) constraint pk_dict_columns primary key,
	ownerid        NUMBER(10),
	modifierid     NUMBER(10),
	creationdate   DATE,
	modifieddate   DATE,
	isactive       CHAR(1) default 'Y' not null,
	columns_name   VARCHAR2(30) not null,
	dict_tables_id NUMBER(10),
	title          VARCHAR2(255),
	notes          VARCHAR2(2000),
	table_name     VARCHAR2(30) not null,
	in_table       CHAR(1) default 'N' not null,
	type           VARCHAR2(255),
	type_value     VARCHAR2(2550),
	is_required    CHAR(1),
	seq            NUMBER(10) default 99 not null
)",
					"comment on column DICT_COLUMNS.columns_name is '字段名'",
					"comment on column DICT_COLUMNS.title is '描述'",
					"comment on column DICT_COLUMNS.notes is '注释'",
					"comment on column DICT_COLUMNS.table_name is '表名'",
					"comment on column DICT_COLUMNS.in_table is '是否在表格中显示（默认N）'",
					"comment on column DICT_COLUMNS.type is '类型（输出框、下拉框等）'",
					"comment on column DICT_COLUMNS.type_value is '类型的值'",
					"comment on column DICT_COLUMNS.is_required is '是否必填'",
					"comment on column DICT_COLUMNS.seq is '排序'",
				),
			),

			array(
				'object_name'		=> "DICT_COLUMNS_SOURCE",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table DICT_COLUMNS_SOURCE
(
	id                  NUMBER(10) constraint pk_dict_columns_source primary key,
	ownerid             NUMBER(10),
	modifierid          NUMBER(10),
	creationdate        DATE,
	modifieddate        DATE,
	isactive            CHAR(1) default 'Y' not null,
	dict_columns_id     NUMBER(10),
	table_name          VARCHAR2(30) not null,
	columns_name        VARCHAR2(300) not null,
	source_columns_id   NUMBER(10),
	source_table_name   VARCHAR2(30) not null,
	source_columns_name VARCHAR2(30) not null,
	source_cols_list    VARCHAR2(1200),
	source_wheres       VARCHAR2(300),
	groups              VARCHAR2(300),
	seq                 NUMBER(10) default 99 not null
)",
					"comment on column DICT_COLUMNS_SOURCE.dict_columns_id is '字段id'",
					"comment on column DICT_COLUMNS_SOURCE.table_name is '字段所在表'",
					"comment on column DICT_COLUMNS_SOURCE.columns_name is '字段'",
					"comment on column DICT_COLUMNS_SOURCE.source_columns_id is '源表字段id'",
					"comment on column DICT_COLUMNS_SOURCE.source_table_name is '源表字段所在表'",
					"comment on column DICT_COLUMNS_SOURCE.source_columns_name is '源字段名'",
					"comment on column DICT_COLUMNS_SOURCE.source_cols_list is '字段显示扩展（显示值）'",
					"comment on column DICT_COLUMNS_SOURCE.groups is '展开子表所在位置'",
					"comment on column DICT_COLUMNS_SOURCE.seq is '主表展开子表时的排序'",
				),
			),

			array(
				'object_name'		=> "DICT_ACTIVE",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table DICT_ACTIVE
(
	id             NUMBER(10) constraint pk_dict_active primary key,
	ownerid        NUMBER(10),
	modifierid     NUMBER(10),
	creationdate   DATE,
	modifieddate   DATE,
	isactive       CHAR(1) default 'Y' not null,
	table_name     VARCHAR2(30),
	dict_tables_id NUMBER(10),
	title          VARCHAR2(255),
	notes          VARCHAR2(2000),
	active_site    VARCHAR2(30),
	active_type    VARCHAR2(255),
	active_main    VARCHAR2(2550),
	active_data    VARCHAR2(2550),
	active_success VARCHAR2(2550)
)",
					"comment on column DICT_ACTIVE.table_name is '表名'",
					"comment on column DICT_ACTIVE.dict_tables_id is '字典id'",
					"comment on column DICT_ACTIVE.title is '描述'",
					"comment on column DICT_ACTIVE.notes is '注释'",
					"comment on column DICT_ACTIVE.active_site is '动作的位置'",
					"comment on column DICT_ACTIVE.active_type is '动作类型（存储过程/接口）'",
					"comment on column DICT_ACTIVE.active_main is '动作'",
					"comment on column DICT_ACTIVE.active_data is '动作所需参数'",
					"comment on column DICT_ACTIVE.active_success is '执行成功后数据回写'",
				),
			),

			array(
				'object_name'		=> "ADMIN_USER",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_USER
(
	id           NUMBER(10) constraint pk_admin_user primary key,
	ownerid      NUMBER(10),
	modifierid   NUMBER(10),
	creationdate DATE,
	modifieddate DATE,
	isactive     CHAR(1) default 'Y' not null,
	username     VARCHAR2(255) not null,
	password     VARCHAR2(255) not null,
	nickname     VARCHAR2(255)
)",
					"comment on column ADMIN_USER.username is '账号'",
					"comment on column ADMIN_USER.password is '密码 '",
					"comment on column ADMIN_USER.nickname is '昵称'",
				),
			),

			array(
				'object_name'		=> "ADMIN_USER_GROUP",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_USER_GROUP
(
	id           NUMBER(10) constraint pk_admin_user_group primary key,
	ownerid      NUMBER(10),
	modifierid   NUMBER(10),
	creationdate DATE,
	modifieddate DATE,
	isactive     CHAR(1) default 'Y' not null,
	title        VARCHAR2(255),
	parent_id    NUMBER(10),
	authority    NUMBER(10)
)",
					"comment on column ADMIN_USER_GROUP.title is '用户组名称'",
					"comment on column ADMIN_USER_GROUP.parent_id is '用户组 - 等级控制'",
					"comment on column ADMIN_USER_GROUP.authority is '权限页面按钮'",
				),
			),

			array(
				'object_name'		=> "ADMIN_USER_GROUP_USER",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_USER_GROUP_USER
(
	id                  NUMBER(10) constraint pk_admin_user_group_user primary key,
	ownerid             NUMBER(10),
	modifierid          NUMBER(10),
	creationdate        DATE,
	modifieddate        DATE,
	isactive            CHAR(1) default 'Y' not null,
	admin_user_group_id NUMBER(10) not null,
	admin_user_id       NUMBER(10) not null
)",
					"comment on column ADMIN_USER_GROUP_USER.admin_user_group_id is '用户组id'",
					"comment on column ADMIN_USER_GROUP_USER.admin_user_id is '用户id'",
				),
			),

			array(
				'object_name'		=> "ADMIN_OPERATE",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_OPERATE
(
	id           NUMBER(10) constraint pk_admin_operate primary key,
	ownerid      NUMBER(10),
	modifierid   NUMBER(10),
	creationdate DATE,
	modifieddate DATE,
	isactive     CHAR(1) default 'Y' not null,
	title        VARCHAR2(255),
	operate      VARCHAR2(255),
	html_url     VARCHAR2(255)
)",
					"comment on column ADMIN_OPERATE.title is '操作名称'",
					"comment on column ADMIN_OPERATE.operate is '操作地址'",
					"comment on column ADMIN_OPERATE.html_url is '页面地址'",
				),
			),

			array(
				'object_name'		=> "ADMIN_MENU",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_MENU
(
	id               NUMBER(10) constraint pk_admin_menu primary key,
	ownerid          NUMBER(10),
	modifierid       NUMBER(10),
	creationdate     DATE,
	modifieddate     DATE,
	isactive         CHAR(1) default 'Y' not null,
	title            VARCHAR2(255),
	admin_operate_id NUMBER(10),
	icon             VARCHAR2(255),
	parent_id        NUMBER(10) not null,
	seq              NUMBER(10) default 99 not null,
	show_type        VARCHAR2(50)
)",
					"comment on column ADMIN_MENU.title is '菜单名称'",
					"comment on column ADMIN_MENU.icon is '菜单图标'",
					"comment on column ADMIN_MENU.parent_id is '等级控制'",
					"comment on column ADMIN_MENU.seq is '排序'",
					"comment on column ADMIN_MENU.show_type is '打开方式'",
				),
			),

			array(
				'object_name'		=> "ADMIN_USER_AUTHORITY",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_USER_AUTHORITY
(
	id                  NUMBER(10) constraint pk_admin_user_authority primary key,
	ownerid             NUMBER(10),
	modifierid          NUMBER(10),
	creationdate        DATE,
	modifieddate        DATE,
	isactive            CHAR(1) default 'Y' not null,
	log_notes           VARCHAR2(255),
	admin_operate_id    NUMBER(10),
	admin_user_group_id NUMBER(10),
	data_authority		VARCHAR2(2550)
)",
					"comment on column ADMIN_USER_AUTHORITY.log_notes is '操作时是否需要填写备注'",
				),
			),

			array(
				'object_name'		=> "ADMIN_CONFIG",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_CONFIG
(
	id           NUMBER(10) constraint pk_admin_config primary key,
	ownerid      NUMBER(10),
	modifierid   NUMBER(10),
	creationdate DATE,
	modifieddate DATE,
	isactive     CHAR(1) default 'Y' not null,
	title        VARCHAR2(255),
	config       VARCHAR2(255),
	value        VARCHAR2(255)
)",
					"comment on column ADMIN_CONFIG.title is '标题'",
					"comment on column ADMIN_CONFIG.config is '配置项'",
					"comment on column ADMIN_CONFIG.value is '值'",
				),
			),

			array(
				'object_name'		=> "ADMIN_SYNC_OUT",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_SYNC_OUT
(
	id             NUMBER(10) constraint pk_admin_sync_out primary key,
	ownerid        NUMBER(10),
	modifierid     NUMBER(10),
	creationdate   DATE,
	modifieddate   DATE,
	isactive       CHAR(1) default 'Y' not null,
	interface_code VARCHAR2(255),
	status         VARCHAR2(64),
	sync_url       VARCHAR2(255),
	post_data      VARCHAR2(2000),
	sync_result    VARCHAR2(255)
)",
					"comment on column ADMIN_SYNC_OUT.interface_code is '接口解释代码（例如vipinfo）'",
					"comment on column ADMIN_SYNC_OUT.status is '状态(待同步,已同步,异常)'",
					"comment on column ADMIN_SYNC_OUT.sync_url is '地址'",
					"comment on column ADMIN_SYNC_OUT.post_data is '传送数据'",
					"comment on column ADMIN_SYNC_OUT.sync_result is '错误信息'",
				),
			),

			array(
				'object_name'		=> "ADMIN_SYNC_IN",
				'object_type'		=> "TABLE",
				'object_value'		=> array(
					"create table ADMIN_SYNC_IN
(
	id             NUMBER(10) constraint pk_admin_sync_in primary key,
	ownerid        NUMBER(10),
	modifierid     NUMBER(10),
	creationdate   DATE,
	modifieddate   DATE,
	isactive       CHAR(1) default 'Y' not null,
	interface_code VARCHAR2(255),
	status         VARCHAR2(64),
	sync_url       VARCHAR2(255),
	post_data      VARCHAR2(2000),
	sync_result    VARCHAR2(255)
)",
					"comment on column ADMIN_SYNC_IN.interface_code is '接口解释代码（例如store）'",
					"comment on column ADMIN_SYNC_IN.status is '状态(待同步,已同步,异常)'",
					"comment on column ADMIN_SYNC_IN.sync_url is '地址'",
					"comment on column ADMIN_SYNC_IN.post_data is '传送数据'",
					"comment on column ADMIN_SYNC_IN.sync_result is '错误信息'",
				),
			),
		);
	}

	public function initInsert(){
		
	}

	public function initInsertData(){
		return $data = array(
			array(
				'table_name'	=> 'DICT_TABLES',
				'list'			=> array(
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'DICT_TABLES',
						'title'			=> '数据字典 - 表',
						'is_menu'		=> 'N',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'DICT_COLUMNS',
						'title'			=> '数据字典 - 字段',
						'is_menu'		=> 'N',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'title'			=> '数据字典 - 外键',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'DICT_ACTIVE',
						'title'			=> '数据字典 - 动作定义',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_CONFIG',
						'title'			=> '相关配置项',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_MENU',
						'title'			=> '后台菜单',
						'is_menu'		=> 'N',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_OPERATE',
						'title'			=> '后台动作',
						'is_menu'		=> 'N',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_USER',
						'title'			=> '后台用户',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_USER_GROUP',
						'title'			=> '后台用户组',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_USER_GROUP_USER',
						'title'			=> '后台用户组 - 用户',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_USER_AUTHORITY',
						'title'			=> '后台用户组 - 权限',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_SYNC_IN',
						'title'			=> '同步接口（进）',
						'is_menu'		=> 'Y',
					),
					array(
						'isactive'		=> 'Y',
						'table_name'	=> 'ADMIN_SYNC_OUT',
						'title'			=> '同步接口（出）',
						'is_menu'		=> 'Y',
					),
				),
			),

			array(
				'table_name'	=> 'DICT_COLUMNS',
				'list'			=> array(
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TABLE_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_TABLES' and dt.isactive='Y')",
						'title'			=> '表名',
						'notes'			=> '',
						'table_name'	=> 'DICT_TABLES',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TITLE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_TABLES' and dt.isactive='Y')",
						'title'			=> '描述',
						'notes'			=> '',
						'table_name'	=> 'DICT_TABLES',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'NOTES',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_TABLES' and dt.isactive='Y')",
						'title'			=> '注释',
						'notes'			=> '',
						'table_name'	=> 'DICT_TABLES',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '3',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'IS_MENU',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_TABLES' and dt.isactive='Y')",
						'title'			=> '是否菜单',
						'notes'			=> '',
						'table_name'	=> 'DICT_TABLES',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '4',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'COLUMNS_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '字段名',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TITLE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '描述',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'NOTES',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '注释',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '3',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TABLE_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '表名',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '4',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'IN_TABLE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '是否在表格中显示（默认N）',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '5',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TYPE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '类型（输出框、下拉框等）',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '6',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TYPE_VALUE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '类型的扩展值',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '7',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'IS_REQUIRED',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS' and dt.isactive='Y')",
						'title'			=> '是否必填',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS',
						'in_table'		=> 'N',
						'type'			=> '',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '8',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TABLE_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> '字段所在表',
						'notes'			=> '大写',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'COLUMNS_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> '字段名',
						'notes'			=> '小写',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'SOURCE_TABLE_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> '源字段所在表',
						'notes'			=> '大写',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '4',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'SOURCE_COLUMNS_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> '源字段',
						'notes'			=> '小写',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '5',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'SOURCE_COLS_LIST',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> '字段显示扩展（显示值）',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '6',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'SOURCE_WHERES',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> 'join_on的其他条件',
						'notes'			=> '',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '7',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'SEQ',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> '子表排序',
						'notes'			=> '主表展开子表时的排序',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '8',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'GROUPS',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_COLUMNS_SOURCE' and dt.isactive='Y')",
						'title'			=> '子表分组',
						'notes'			=> '展开子表所在位置,不设置时默认为0',
						'table_name'	=> 'DICT_COLUMNS_SOURCE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '9',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ACTIVE_DATA',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '动作所需参数',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'N',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ACTIVE_MAIN',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '动作',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ACTIVE_SITE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '动作的位置',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'Y',
						'type'			=> 'select',
						'type_value'	=> '{"group_1":{"select_option_title":"仅新增","select_option_value":"insert"},"group_2":{"select_option_title":"新增和编辑","select_option_value":"edit"},"group_3":{"select_option_title":"仅编辑","select_option_value":"jedit"}}',
						'is_required'	=> '',
						'seq'			=> '3',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ACTIVE_SUCCESS',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '执行成功后数据回写',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'N',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '4',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TITLE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '描述',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '5',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TABLE_NAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '表名',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '6',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'DICT_TABLES_ID',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '字典id',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '7',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'NOTES',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '注释',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '8',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ACTIVE_TYPE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='DICT_ACTIVE' and dt.isactive='Y')",
						'title'			=> '动作类型（存储过程/接口）',
						'notes'			=> '',
						'table_name'	=> 'DICT_ACTIVE',
						'in_table'		=> 'Y',
						'type'			=> 'select',
						'type_value'	=> '{"group_1":{"select_option_title":"接口","select_option_value":"sync"},"group_2":{"select_option_title":"存储过程","select_option_value":"proc"}}',
						'is_required'	=> '',
						'seq'			=> '9',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'USERNAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER' and dt.isactive='Y')",
						'title'			=> '账号',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'PASSWORD',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER' and dt.isactive='Y')",
						'title'			=> '密码',
						'notes'			=> '请填入对密码进行md5(小写)加密后的字符串，可参考http://tool.chinaz.com/tools/md5.aspx',
						'table_name'	=> 'ADMIN_USER',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'NICKNAME',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER' and dt.isactive='Y')",
						'title'			=> '昵称',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '3',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TITLE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_GROUP' and dt.isactive='Y')",
						'title'			=> '用户组名称',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_GROUP',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'AUTHORITY',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_GROUP' and dt.isactive='Y')",
						'title'			=> '权限管理',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_GROUP',
						'in_table'		=> 'Y',
						'type'			=> 'button',
						'type_value'	=> '{"button_name":"权限管理","button_href":"/UserAuthority/authority.html","button_click":"","group_1":{"button_param_key":"admin_user_group_id","button_param_table":"ADMIN_USER_GROUP","button_param_column":"id","button_param_value":""}}',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ADMIN_USER_ID',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_GROUP_USER' and dt.isactive='Y')",
						'title'			=> '用户id',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_GROUP_USER',
						'in_table'		=> 'Y',
						'type'			=> 'select',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ADMIN_USER_GROUP_ID',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_GROUP_USER' and dt.isactive='Y')",
						'title'			=> '用户组id',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_GROUP_USER',
						'in_table'		=> 'Y',
						'type'			=> 'select',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ADMIN_USER_GROUP_ID',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_AUTHORITY' and dt.isactive='Y')",
						'title'			=> '用户组id',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_AUTHORITY',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'ADMIN_OPERATE_ID',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_AUTHORITY' and dt.isactive='Y')",
						'title'			=> '操作id',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_AUTHORITY',
						'in_table'		=> 'Y',
						'type'			=> 'input',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'LOG_NOTES',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_AUTHORITY' and dt.isactive='Y')",
						'title'			=> '操作时是否需要填写备注',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_AUTHORITY',
						'in_table'		=> 'Y',
						'type'			=> 'radio',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '3',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'DATA_AUTHORITY',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_USER_AUTHORITY' and dt.isactive='Y')",
						'title'			=> '数据权限',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_USER_AUTHORITY',
						'in_table'		=> 'Y',
						'type'			=> 'text',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '4',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'HTML_URL',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_OPERATE' and dt.isactive='Y')",
						'title'			=> '页面地址',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_OPERATE',
						'in_table'		=> 'Y',
						'type'			=> 'text',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '1',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'TITLE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_OPERATE' and dt.isactive='Y')",
						'title'			=> '操作名称',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_OPERATE',
						'in_table'		=> 'Y',
						'type'			=> 'text',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '2',
					),
					array(
						'isactive'		=> 'Y',
						'columns_name'	=> 'OPERATE',
						'dict_tables_id'=> "(select min(dt.id) from dict_tables dt where dt.table_name='ADMIN_OPERATE' and dt.isactive='Y')",
						'title'			=> '操作地址',
						'notes'			=> '',
						'table_name'	=> 'ADMIN_OPERATE',
						'in_table'		=> 'Y',
						'type'			=> 'text',
						'type_value'	=> '',
						'is_required'	=> '',
						'seq'			=> '3',
					),
				),
			),

			array(
				'table_name'	=> 'ADMIN_OPERATE',
				'list'			=> array(
					array(
						'isactive'		=> 'Y',
						'title'			=> '数据字典',
						'operate'		=> 'Dict/tables',
						'html_url'		=> 'Dict/dict.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> 'OM-操作管理',
						'operate'		=> 'Operate/index',
						'html_url'		=> 'Operate/index.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> 'OM-菜单列表',
						'operate'		=> 'Operate/menu',
						'html_url'		=> 'Operate/menu.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> 'OM-编辑操作',
						'operate'		=> 'Operate/edit',
						'html_url'		=> 'Operate/index.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> 'OM-编辑菜单',
						'operate'		=> 'Operate/editMenu',
						'html_url'		=> 'Operate/menu.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '外键关联',
						'operate'		=> 'Portal/table_name/DICT_COLUMNS_SOURCE/index',
						'html_url'		=> 'Portal/index.html?table_name=DICT_COLUMNS_SOURCE',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '动作定义',
						'operate'		=> 'Portal/table_name/DICT_ACTIVE/index',
						'html_url'		=> 'Portal/index.html?table_name=DICT_ACTIVE',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '主页',
						'operate'		=> 'Index/index',
						'html_url'		=> 'Index/index.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '首页',
						'operate'		=> 'Index/home',
						'html_url'		=> 'Index/home.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '系统设置',
						'operate'		=> 'Index/init',
						'html_url'		=> 'Index/init.html',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '后台用户列表',
						'operate'		=> 'Portal/table_name/ADMIN_USER/index',
						'html_url'		=> 'Portal/index.html?table_name=ADMIN_USER',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '后台用户组列表',
						'operate'		=> 'Portal/table_name/ADMIN_USER_GROUP/index',
						'html_url'		=> 'Portal/index.html?table_name=ADMIN_USER_GROUP',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '后台用户组-用户列表',
						'operate'		=> 'Portal/table_name/ADMIN_USER_GROUP_USER/index',
						'html_url'		=> 'Portal/index.html?table_name=ADMIN_USER_GROUP_USER',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '后台用户权限列表',
						'operate'		=> 'Portal/table_name/ADMIN_USER_AUTHORITY/index',
						'html_url'		=> 'Portal/index.html?table_name=ADMIN_USER_AUTHORITY',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '相关配置',
						'operate'		=> 'Portal/table_name/ADMIN_CONFIG/index',
						'html_url'		=> 'Portal/index.html?table_name=ADMIN_CONFIG',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '接口失败数据 - 进',
						'operate'		=> 'Portal/table_name/ADMIN_SYNC_IN/index',
						'html_url'		=> 'Portal/index.html?table_name=ADMIN_SYNC_IN',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '接口失败数据 - 出',
						'operate'		=> 'Portal/table_name/ADMIN_SYNC_OUT/index',
						'html_url'		=> 'Portal/index.html?table_name=ADMIN_SYNC_OUT',
					),
					array(
						'isactive'		=> 'Y',
						'title'			=> '上传图片',
						'operate'		=> 'Tool/uploadImg',
						'html_url'		=> '',
					),
				),
			),

			array(
				'table_name'	=> 'ADMIN_MENU',
				'list'			=> array(
					array(
						'isactive'			=> 'Y',
						'title'				=> '主页',
						'admin_operate_id'	=> "",
						'icon'				=> '',
						'parent_id'			=> '0',
						'seq'				=> '1',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '后台管理',
						'admin_operate_id'	=> "",
						'icon'				=> '',
						'parent_id'			=> '0',
						'seq'				=> '2',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '首页',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Index/home' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='主页' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '1',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '系统设置',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Index/init' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='主页' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '2',
						'show_type'			=> '_blank',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '数据字典',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Dict/tables' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '1',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '操作管理',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Operate/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '2',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '菜单管理',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Operate/menu' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '3',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '外键关联',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Portal/table_name/DICT_COLUMNS_SOURCE/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '4',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '动作定义',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Portal/table_name/DICT_ACTIVE/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '5',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '后台用户',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Portal/table_name/ADMIN_USER/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '6',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '后台用户组',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Portal/table_name/ADMIN_USER_GROUP/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '7',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '后台用户组-用户',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Portal/table_name/ADMIN_USER_GROUP_USER/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '8',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '后台用户组-权限',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Portal/table_name/ADMIN_USER_AUTHORITY/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '9',
						'show_type'			=> '',
					),
					array(
						'isactive'			=> 'Y',
						'title'				=> '相关配置',
						'admin_operate_id'	=> "(select min(o.id) from admin_operate o where o.operate='Portal/table_name/ADMIN_CONFIG/index' and o.isactive='Y')",
						'icon'				=> '',
						'parent_id'			=> "(select min(m.id) from admin_menu m where m.title='后台管理' and m.isactive='Y' and m.parent_id='0')",
						'seq'				=> '10',
						'show_type'			=> '',
					),
				),
			),
			array(
				'table_name'	=> 'DICT_COLUMNS_SOURCE',
				'list'			=> array(
					array(
						'isactive'				=> 'Y',
						'table_name'			=> 'ADMIN_USER_GROUP_USER',
						'columns_name'			=> "admin_user_id",
						'source_table_name'		=> 'ADMIN_USER',
						'source_columns_name'	=> 'id',
						'source_cols_list'		=> 'username',
					),
					array(
						'isactive'				=> 'Y',
						'table_name'			=> 'ADMIN_USER_GROUP_USER',
						'columns_name'			=> "admin_user_group_id",
						'source_table_name'		=> 'ADMIN_USER_GROUP',
						'source_columns_name'	=> 'id',
						'source_cols_list'		=> 'title',
					),
					array(
						'isactive'				=> 'Y',
						'table_name'			=> 'ADMIN_USER_AUTHORITY',
						'columns_name'			=> "admin_user_group_id",
						'source_table_name'		=> 'ADMIN_USER_GROUP',
						'source_columns_name'	=> 'id',
						'source_cols_list'		=> 'title',
					),
					array(
						'isactive'				=> 'Y',
						'table_name'			=> 'ADMIN_USER_AUTHORITY',
						'columns_name'			=> "admin_operate_id",
						'source_table_name'		=> 'ADMIN_OPERATE',
						'source_columns_name'	=> 'id',
						'source_cols_list'		=> 'title',
					),
				),
			),
		);
	}
}		
